server:
  port: 8090

logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Drive
    url: jdbc:mysql://localhost:3306/obook
    username: root
    password: 1018
